package com.singlefood.sinfo.utils;

public class Constants {
    public static String[] foods = {"Adobo de chancho",
            "Aguadito",
            "Ajiaco de Papas",
            "Ají de Gallina",
            "Alverjado de Pollo",
            "Anticuchos",
            "Arroz a la jardinera",
            "Arroz Chaufa",
            "Arroz chaufa de mariscos",
            "Arroz con mariscos",
            "Arroz con pato",
            "Arroz con pollo",
            "Arroz tapado",
            "Bistec a lo pobre",
            "Bistec a la chorrilana",
            "Cabrito a la norteña",
            "Caldo de cabeza de carnero o cordero",
            "Caldo de gallina",
            "Cancancho o cordero al palo",
            "Cau cau",
            "Causa",
            "Causa lambayecana o ferreñafana",
            "Ceviche",
            "Ceviche de conchas negras",
            "Ceviche de camarones",
            "Ceviche mixto",
            "Carapulcra",
            "Cuy chactado",
            "Chacharada o cacharrada",
            "Chairo",
            "Chanfainita",
            "Charquicán",
            "Chaque",
            "Chicharrones",
            "Chilcano",
            "Chinguirito",
            "Chirimpico",
            "Choros a la chalaca",
            "Chupe de cangrejos",
            "Chupe de camarones",
            "Chupe verde o Yacuchupe",
            "Escabeche",
            "Escribano",
            "Estofado",
            "Espesado",
            "Frito trujillano",
            "Hígado encebollado",
            "Huatía",
            "Inchicapi",
            "Jalea",
            "Juane",
            "Locro",
            "Locro de gallina",
            "Lomo saltado",
            "Malaya",
            "Majarisco",
            "Menestrón",
            "Migadito",
            "Mondonguito a la italiana",
            "Ocopa",
            "Olluquito con charqui",
            "Pachamanca",
            "Papa a la Huancaína",
            "Papa rellena",
            "Parihuela",
            "Patachi o sopa de trigo",
            "Patarashca",
            "Patasca",
            "Patitas con maní",
            "Pepian de choclo",
            "Pesque de quinua",
            "Pescado a lo macho",
            "Picante a la tacneña",
            "Picante de cuy",
            "Pollo broaster",
            "Pollo a la brasa",
            "Pollo al sillao",
            "Puca picante",
            "Quinua atamalada",
            "Rocoto relleno",
            "Salchipapa",
            "Sancochado",
            "Seco de chabelo",
            "Seco de res con frejoles",
            "Seco a la norteña",
            "Shambar",
            "Solterito",
            "Sopa criolla",
            "Sopa de choros",
            "Sopa seca",
            "Sopa teóloga",
            "Sudado de pescado",
            "Tacacho con cecina",
            "Tacu tacu",
            "Tallarín saltado",
            "Tallarines rojos con pollo",
            "Tallarines verdes",
            "Tiradito",
            "Tortilla de raya",
            "Trucha frita"};
}
